# Generated by Django 5.1.5 on 2025-02-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('popular', 'Popular'), ('top_rated', 'Top Rated'), ('upcoming', 'Upcoming'), ('now_playing', 'Now Playing')], default='popular', max_length=20),
        ),
    ]
