# Generated by Django 5.1.5 on 2025-02-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
