# Generated by Django 5.1.5 on 2025-02-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_alter_movie_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
